# PREFIX KEY SETUP
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# SOURCE FILE KEY
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# TERMINAL/TRUECOLOR SETUP
set -g default-terminal "tmux-256color"
set -s terminal-features "xterm*:clipboard:ccolour:cstyle:focus:title:mouse"
set -s terminal-overrides "xterm-256color:RGB,*:Tc"
set -sg escape-time 10

# INDEXING
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# MOUSE
set -g mouse on

# HISTORY
set -g history-limit 10000

# SPLITS
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# PANE NAVIGATION(M stands for Meta, ie, your ALT key)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# PANE RESIZING
bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5
bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5

# TPC plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# STATUS BAR
set -g status on

set -g status-position bottom  # top or bottom
set -g status-interval 15 # refresh rate

set -g status-left ""  # shows the stuff displayed on the left side
set -g status-left-length 0 # max length of the left section
set -g status-right "" # shows the stuff displayed on the right side
set -g status-right-length 0 # max length of the right section


set -g status-style "bg=#010101,fg=#cdd6f4"  # color and attributes of the status bar background

set -g status-justify centre

set -g status-interval 1

# ---

# dracula theme
# set -g @plugin 'dracula/tmux'
# set -g @dracula-show-powerline true
# set -g @dracula-plugins "cpu-usage ram-usage time"

# WINDOWS
setw -g window-status-separator " "  # the separator b/w windows

# set the colors for the inactive windows - using starship first box color #5D8A5D
setw -g window-status-format " #I: #W "
setw -g window-status-style \
    "bg=#5D8A5D,fg=#F0FFF0"

# set the colors for the active windows - lighter green variant
setw -g window-status-current-format " #I: #W "
setw -g window-status-current-style \
    "bg=#395539,fg=#ffffff,bold"

# MESSAGES
set -g message-style "bg=#000000,fg=#89b4fa"
set -g mode-style "bg=#89b4fa,fg=#000000"

# RENAMING
setw -g automatic-rename on
set -g allow-rename on

# VIM mode-style
setw -g mode-keys vi

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Resurrect
set -g @resurrect-capture-pane-contents 'on'

# Continuum
set -g @continuum-restore 'off'    # restores on launching tmux
set -g @continuum-save-interval '15'

# INITIALIZE TPM
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'


set -g mouse on
